### ISSUE TITLE
Replace makefile with Meson

### ISSUE THREAD

**Issue by gavr123456789** [bynect/mongo-vapi#1]
https://mesonbuild.com/Vala.html

**Comment by bynect** [comment]
Hello, I am looking into it as an alternative build method.
I am unsure if should I use options (-D) for building tests/examples since meson don't have multiple target (that I am aware of).

**Comment by bynect** [comment]
I have added a meson script for building test and samples. Since the copy-paste logic is handled by the python script it simply calls it (like the Makefile).
Anyway, I would appreciate if you give me some feedback about it.

**Comment by gavr123456789** [comment]
Thanks, just tested build with meson, all works great.  
![image](https://user-images.githubusercontent.com/30507409/103540901-8acd0c00-4eab-11eb-98e5-4d3560f0afdd.png)

**Comment by gavr123456789** [comment]
Also you forget to say about `ninja -C build` after `meson build` in README

**Comment by bynect** [comment]
Just updated the README 👍
